include(CheckCXXCompilerFlag)
macro(add_cxx_flag_if_available WHICH_FLAGS FLAG)
  set(FLAG_OK)
  check_cxx_compiler_flag("${FLAG}" FLAG_OK)
  if(FLAG_OK)
    string(APPEND ${WHICH_FLAGS} " ${FLAG}")
  endif()
endmacro()
add_cxx_flag_if_available(CMAKE_CXX_FLAGS "-Wall")
add_cxx_flag_if_available(CMAKE_CXX_FLAGS "-Wextra")
add_cxx_flag_if_available(CMAKE_CXX_FLAGS_DEBUG "-fno-omit-frame-pointer")
add_cxx_flag_if_available(CMAKE_CXX_FLAGS_DEBUG "-fsanitize=address")
message(STATUS "CXX Flags: ${CMAKE_CXX_FLAGS}")
message(STATUS "CXX Flags Debug: ${CMAKE_CXX_FLAGS_DEBUG}")


